
services:
    web:
        image: nginx:1.25.3-alpine
        container_name: web-staffmaster
        working_dir: /app
        volumes:
            - ./docker/production/nginx/config.conf:/etc/nginx/conf.d/default.conf
            - .:/app
        networks:
            - app-net
        ports:
            - $APP_PORT:80
        depends_on:
            - php

    php:
        container_name: php-staffmaster
        working_dir: /app
        user: $DOCKER_USER
        volumes:
            - .:/app
        build:
            context: .
            dockerfile: ./docker/production/php/Dockerfile
        networks:
            - app-net
        depends_on:
            database:
                condition: service_healthy
            redis:
                condition: service_healthy

    database:
        container_name: database-staffmaster
        working_dir: /app
        image: postgres:16.1-alpine3.19
        environment:
            POSTGRES_DB:  ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data_prod:/var/lib/postgresql/data
        networks:
            - app-net
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
            interval: 5s
            timeout: 5s
            retries: 5

    redis:
        image: redis:7.2.3-alpine
        container_name: redis-staffmaster
        command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
        networks:
            - app-net
        volumes:
            - redis_data_prod:/data
        healthcheck:
            test: ["CMD", "redis-cli","ping"]
            interval: 5s
            timeout: 5s
            retries: 5

    node:
        build:
            context: .
            dockerfile: ./docker/production/node/Dockerfile
        container_name: node-staffmaster
        user: $DOCKER_USER
        working_dir: /app
        tty: true
        ports:
            - $NODE_PORT:5173
        volumes:
            - .:/app
        networks:
            - app-net
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin-staffmaster
        ports:
            - "8888:80"
        networks:
            - app-net
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        volumes:
            - pgadmin_data_prod:/var/lib/pgadmin
networks:
    app-net:
        driver: bridge

volumes:
    db_data_prod:
    redis_data_prod:
    pgadmin_data_prod:
